# Generated by Django 4.2.27 on 2026-02-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Program', 'Program')], default='Theory', max_length=20),
        ),
    ]
