# Generated by Django 4.2.27 on 2026-02-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_current_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
