# Generated by Django 4.2.27 on 2026-02-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrequest',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loginrequest',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginrequest',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
