# Generated by Django 5.2.11 on 2026-03-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_loginrequest_device_info_loginrequest_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrequest',
            name='login_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
