# Generated by Django 5.2.11 on 2026-03-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_loginrequest_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
