# Generated by Django 5.2.11 on 2026-02-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_results_published'),
        ('security', '0002_lab_allowedip_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='labs',
            field=models.ManyToManyField(blank=True, help_text='Restrict exam to specific labs', to='security.lab'),
        ),
        migrations.AddField(
            model_name='exam',
            name='warning_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Max violations before automatic submission'),
        ),
    ]
