# Generated by Django 5.2.11 on 2026-02-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_labs_exam_warning_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamattempt',
            name='violation_count',
            field=models.IntegerField(default=0),
        ),
    ]
