# Generated by Django 4.2.27 on 2026-02-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_studentexamattempt_violation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='random_question_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of questions to pick randomly for each student. If empty, ALL questions are shown.', null=True),
        ),
    ]
