# Generated by Django 4.2.27 on 2026-02-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_random_question_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(blank=True, help_text='If set, only effective for this exam. If empty, global.', null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
            ],
        ),
    ]
