# Generated by Django 4.2.27 on 2026-02-09 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0006_examannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='examannouncement',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='If set, only this specific student will see the message.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_announcements', to=settings.AUTH_USER_MODEL),
        ),
    ]
