# Generated by Django 4.2.27 on 2026-02-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_examannouncement_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='program_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of Program questions to pick for this exam.', null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='theory_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of Theory questions to pick for this exam.', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='random_question_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of random questions. If set, logic below applies.', null=True),
        ),
    ]
