# Generated by Django 5.2.11 on 2026-02-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Lab-A, Lab-B', max_length=100, unique=True)),
                ('ip_range_start', models.GenericIPAddressField(help_text='Start of IP range')),
                ('ip_range_end', models.GenericIPAddressField(help_text='End of IP range')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='allowedip',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_ips', to='security.lab'),
        ),
    ]
